# basic options
title: Vakantie MAAND JAAR - BESTEMMING
author: Kees
description: Blog van de vakantie van MAAND JAAR

# URL to GitHub repo
baseurl: "/template-vakantie-blog" 
url: "https://prudento-nl.github.io" 

# URL to images folder at GitHub repo LET OP het format van de link met de PUNT!
images: "https://prudento-nl.github.io/template-vakantie-blog/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
